spring:
  datasource:
    url: jdbc:mysql://localhost:3306/point_of_sale?useSSL=false
    username: root
    password:

#JPA Settings
  jpa:
    hibernate:
      ddl-auto: update

server:
  error:
    include-message: always